version: "3.8"
services:
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/server
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/client
      - /client/node_modules
